#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/fcnt/itc

PRODUCT_COPY_FILES += \
    vendor/fcnt/itc/proprietary/product/etc/sysconfig/euicc.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/euicc.xml \
    vendor/fcnt/itc/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/fcnt/itc/proprietary/system_ext/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.fingerprints.extension.xml \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/04010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/04010000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/fcnt/itc/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/fcnt/itc/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/AudioLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AudioLog_dynamic.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/apdb/APDB_MT6855___W2409:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6855___W2409 \
    vendor/fcnt/itc/proprietary/vendor/etc/apdb/APDB_MT6855___W2409_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6855___W2409_ENUM \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/AudioParamOptions_mgvi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_mgvi.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/aurisys_config_rv.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_rv.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/arcsoft_portrait_super_night_se_raw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/arcsoft_portrait_super_night_se_raw.bin \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/calib/1st/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/calib/1st/vidhance_calibration \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/calib/2nd/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/calib/2nd/vidhance_calibration \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/hdrcfg.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdrcfg.cfg \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/inside/3.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/inside/3.mslut \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/inside/383BF935-C597-4F6E-80E7-6B47AAF7A04F.1.facemesh:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/inside/383BF935-C597-4F6E-80E7-6B47AAF7A04F.1.facemesh \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/inside/AAD90D4A-F387-4E9E-B9C5-DA255398CA7E.1.facemesh:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/inside/AAD90D4A-F387-4E9E-B9C5-DA255398CA7E.1.facemesh \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/inside/info_new.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/inside/info_new.json \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/inside/ms_face_v2.0.9.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/inside/ms_face_v2.0.9.model \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/outside/4.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/outside/4.mslut \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/outside/63BD3F32-D01B-4755-92D5-0DE361E4045A.3.facemesh:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/outside/63BD3F32-D01B-4755-92D5-0DE361E4045A.3.facemesh \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/outside/AAD90D4A-F387-4E9E-B9C5-DA255398CA7E.1.facemesh:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/outside/AAD90D4A-F387-4E9E-B9C5-DA255398CA7E.1.facemesh \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/outside/info_new.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/outside/info_new.json \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/model/outside/ms_face_v2.0.9.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/outside/ms_face_v2.0.9.model \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/sr_models.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_models.bin \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/super_night_raw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/super_night_raw.bin \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/user.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/user.cfg \
    vendor/fcnt/itc/proprietary/vendor/etc/camera/vidhance.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance.lic \
    vendor/fcnt/itc/proprietary/vendor/etc/default_pd_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/etc/default_pd_calibration.bin \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_DCM.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_DCM.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/init.insmod.mt6855.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.mt6855.cfg \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.security.keymint-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.trustonic.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/android.hardware.sensors@2.0-service.multihal-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@2.0-service.multihal-mediatek.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/atcid.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/atcid.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/audiocmdservice_atci.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/audiocmdservice_atci.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/bootperf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bootperf.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/init.bip_ap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip_ap.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/init.cccifsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccifsd.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/memtrack-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack-mediatek.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/networksetting.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/networksetting.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/fcnt/itc/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/fcnt/itc/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/fcnt/itc/proprietary/vendor/etc/meow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/meow.cfg \
    vendor/fcnt/itc/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/fcnt/itc/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/fcnt/itc/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/fcnt/itc/proprietary/vendor/etc/permissions/com.mediatek.hardware.vow_dsp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.mediatek.hardware.vow_dsp.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/fcnt/itc/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/fcnt/itc/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/fcnt/itc/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/fcnt/itc/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/fcnt/itc/proprietary/vendor/etc/seccomp_policy/mediaswcodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaswcodec.policy \
    vendor/fcnt/itc/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/fcnt/itc/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/fcnt/itc/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/fcnt/itc/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/GC7202_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/GC7202_mp.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/HQ_YAMATO_MDT_6P088_JD9365T-FW_Release_Version_History_0513.xlsx:$(TARGET_COPY_OUT_VENDOR)/firmware/HQ_YAMATO_MDT_6P088_JD9365T-FW_Release_Version_History_0513.xlsx \
    vendor/fcnt/itc/proprietary/vendor/firmware/ReleaseNote_20240522.xls:$(TARGET_COPY_OUT_VENDOR)/firmware/ReleaseNote_20240522.xls \
    vendor/fcnt/itc/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1b_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1b_1.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1c_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1c_1.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LCE_MDT_JD0103.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LCE_MDT_JD0103.txt \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LCE_MDT_JD010F.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LCE_MDT_JD010F.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LCE_MDT_JD0110.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LCE_MDT_JD0110.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LCE_MDT_JD0111.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LCE_MDT_JD0111.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LD_MDT_GC0202_MP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LD_MDT_GC0202_MP.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LD_MDT_GC0203_MP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LD_MDT_GC0203_MP.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LD_MDT_GC020E.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LD_MDT_GC020E.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LD_MDT_GC020F.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LD_MDT_GC020F.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/Yamato_LD_MDT_GC0210.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Yamato_LD_MDT_GC0210.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/aw862x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw862x_haptic.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/aw862xx_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw862xx_haptic.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/aw883xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw883xx_acf.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/gcore_mp_test.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/gcore_mp_test.ini \
    vendor/fcnt/itc/proprietary/vendor/firmware/haptic_nv_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_nv_rtp.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/haptic_nv_rtp_autosin.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_nv_rtp_autosin.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/haptic_nv_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_nv_rtp_lighthouse.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/haptic_nv_rtp_osc_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_nv_rtp_osc_24K_5s.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/haptic_nv_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_nv_rtp_silk.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/ho0.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/ho0.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/ho1.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/ho1.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/ho2.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/ho2.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/ho3.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/ho3.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/ho4.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/ho4.cfg \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6627_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6627_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6630_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6630_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6630_fm_v2_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6630_fm_v2_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff_tx.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6630_fm_v2_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6630_fm_v2_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch_tx.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6632_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6632_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/fcnt/itc/proprietary/vendor/firmware/rgx.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.fw \
    vendor/fcnt/itc/proprietary/vendor/firmware/rgx.sh:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.sh \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc2_2_ram_bt_1b_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1b_1_hdr.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc2_2_ram_bt_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1c_1_hdr.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc2_2_ram_mcu_1b_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1b_1_hdr.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc2_2_ram_mcu_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1c_1_hdr.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc2_2_ram_wifi_1b_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1b_1_hdr.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc2_2_ram_wifi_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1c_1_hdr.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_coeff.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/soc_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_patch.bin \
    vendor/fcnt/itc/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/fcnt/itc/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libEGL_mtk \
    libGLESv1_CM_mtk \
    libGLESv2_mtk \
    hi1339_mipi_raw_IdxMgr \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.rogue \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mtk \
    sound_trigger.primary.default \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    imx350_mipi_raw_IdxMgr \
    imx386_mipi_mono_IdxMgr \
    imx386_mipi_raw_IdxMgr \
    imx398_mipi_raw_IdxMgr \
    imx481_mipi_raw_IdxMgr \
    imx499_mipi_raw_IdxMgr \
    imx519_mipi_raw_IdxMgr \
    imx586_mipi_raw_IdxMgr \
    libAVCSecureVencCA \
    libCamera_mtk000mipiraw_E2EHDR_Preview \
    libCamera_mtk000mipiraw_E2EHDR_Video \
    libCamera_mtk000mipiraw_Face_Capture \
    libCamera_mtk000mipiraw_Flash_Capture \
    libCamera_mtk000mipiraw_HDR_Capture \
    libCamera_mtk000mipiraw_HDR_Preview \
    libCamera_mtk000mipiraw_HDR_Reconfig_Preview \
    libCamera_mtk000mipiraw_HDR_Reconfig_Video \
    libCamera_mtk000mipiraw_HDR_Video \
    libCamera_mtk000mipiraw_N3D_Capture \
    libCamera_mtk000mipiraw_N3D_Preview \
    libCamera_mtk000mipiraw_N3D_Video \
    libCamera_mtk000mipiraw_P1_YUV \
    libCamera_mtk000mipiraw_Scene_Capture \
    libCamera_mtk000mipiraw_Scene_Capture_4cell \
    libCamera_mtk000mipiraw_Scene_Preview \
    libCamera_mtk000mipiraw_Scene_Preview_4k \
    libCamera_mtk000mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_mtk000mipiraw_Video_1080 \
    libCamera_mtk000mipiraw_Video_4k \
    libCamera_s5k4h7mipiraw_Beauty_Capture \
    libCamera_s5k4h7mipiraw_Beauty_Preview \
    libCamera_s5k4h7mipiraw_Bokeh_Capture \
    libCamera_s5k4h7mipiraw_Bokeh_Preview \
    libCamera_s5k4h7mipiraw_E2EHDR_Preview \
    libCamera_s5k4h7mipiraw_E2EHDR_Video \
    libCamera_s5k4h7mipiraw_Face_ASD_Capture \
    libCamera_s5k4h7mipiraw_Face_ASD_Preview \
    libCamera_s5k4h7mipiraw_Face_Capture \
    libCamera_s5k4h7mipiraw_Face_Capture_3rd_party \
    libCamera_s5k4h7mipiraw_Face_Preview \
    libCamera_s5k4h7mipiraw_Face_Preview_3rd_party \
    libCamera_s5k4h7mipiraw_Flash_Capture \
    libCamera_s5k4h7mipiraw_HDR_Capture \
    libCamera_s5k4h7mipiraw_HDR_Preview \
    libCamera_s5k4h7mipiraw_HDR_Reconfig_Preview \
    libCamera_s5k4h7mipiraw_HDR_Reconfig_Video \
    libCamera_s5k4h7mipiraw_HDR_Video \
    libCamera_s5k4h7mipiraw_Manual_Capture \
    libCamera_s5k4h7mipiraw_Manual_Preview \
    libCamera_s5k4h7mipiraw_N3D_Capture \
    libCamera_s5k4h7mipiraw_N3D_Preview \
    libCamera_s5k4h7mipiraw_N3D_Video \
    libCamera_s5k4h7mipiraw_P1_YUV \
    libCamera_s5k4h7mipiraw_Scene_Capture \
    libCamera_s5k4h7mipiraw_Scene_Capture_3rd_party \
    libCamera_s5k4h7mipiraw_Scene_Capture_4cell \
    libCamera_s5k4h7mipiraw_Scene_Preview \
    libCamera_s5k4h7mipiraw_Scene_Preview_3rd_party \
    libCamera_s5k4h7mipiraw_Scene_Preview_4k \
    libCamera_s5k4h7mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k4h7mipiraw_Video_1080 \
    libCamera_s5k4h7mipiraw_Video_4k \
    libCamera_s5k4h7mipiraw_Video_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Beauty_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Beauty_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_Bokeh_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Bokeh_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_E2EHDR_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_E2EHDR_Video \
    libCamera_s5k4h7sunnyfrontmipiraw_Face_ASD_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Face_ASD_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_Face_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Face_Capture_3rd_party \
    libCamera_s5k4h7sunnyfrontmipiraw_Face_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_Face_Preview_3rd_party \
    libCamera_s5k4h7sunnyfrontmipiraw_Flash_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_HDR_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_HDR_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_HDR_Reconfig_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_HDR_Reconfig_Video \
    libCamera_s5k4h7sunnyfrontmipiraw_HDR_Video \
    libCamera_s5k4h7sunnyfrontmipiraw_Manual_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Manual_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_N3D_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_N3D_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_N3D_Video \
    libCamera_s5k4h7sunnyfrontmipiraw_P1_YUV \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Capture \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Capture_3rd_party \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Capture_4cell \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Preview \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Preview_3rd_party \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Preview_4k \
    libCamera_s5k4h7sunnyfrontmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k4h7sunnyfrontmipiraw_Video_1080 \
    libCamera_s5k4h7sunnyfrontmipiraw_Video_Capture \
    libCamera_s5kjnsmipiraw_3rd_Capture_mfnr \
    libCamera_s5kjnsmipiraw_3rd_Face_Capture_mfnr \
    libCamera_s5kjnsmipiraw_ASD_Capture \
    libCamera_s5kjnsmipiraw_ASD_Face_Capture \
    libCamera_s5kjnsmipiraw_ASD_Face_Preview \
    libCamera_s5kjnsmipiraw_ASD_Preview \
    libCamera_s5kjnsmipiraw_E2EHDR_Preview \
    libCamera_s5kjnsmipiraw_E2EHDR_Video \
    libCamera_s5kjnsmipiraw_FaceBeauty_Captute \
    libCamera_s5kjnsmipiraw_Face_Capture \
    libCamera_s5kjnsmipiraw_Face_Capture_Torch \
    libCamera_s5kjnsmipiraw_Face_Preview \
    libCamera_s5kjnsmipiraw_Flash_Capture \
    libCamera_s5kjnsmipiraw_Flash_Preview \
    libCamera_s5kjnsmipiraw_HDR_Capture \
    libCamera_s5kjnsmipiraw_HDR_Face_Capture \
    libCamera_s5kjnsmipiraw_HDR_Face_Preview \
    libCamera_s5kjnsmipiraw_HDR_Preview \
    libCamera_s5kjnsmipiraw_Manual_Capture \
    libCamera_s5kjnsmipiraw_Manual_Face_Capture \
    libCamera_s5kjnsmipiraw_Manual_Face_Preview \
    libCamera_s5kjnsmipiraw_Manual_Preview \
    libCamera_s5kjnsmipiraw_N3D_Capture \
    libCamera_s5kjnsmipiraw_N3D_Preview \
    libCamera_s5kjnsmipiraw_N3D_Video \
    libCamera_s5kjnsmipiraw_P1_YUV \
    libCamera_s5kjnsmipiraw_Portrait_Capture \
    libCamera_s5kjnsmipiraw_Portrait_Preview \
    libCamera_s5kjnsmipiraw_Scene_Capture \
    libCamera_s5kjnsmipiraw_Scene_Capture_4cell \
    libCamera_s5kjnsmipiraw_Scene_Capture_Torch \
    libCamera_s5kjnsmipiraw_Scene_Preview \
    libCamera_s5kjnsmipiraw_Scene_Preview_4k \
    libCamera_s5kjnsmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5kjnsmipiraw_SuperNight_Face_Capture \
    libCamera_s5kjnsmipiraw_SuperNight_Face_Preview \
    libCamera_s5kjnsmipiraw_SuperNight_Scene_Capture \
    libCamera_s5kjnsmipiraw_SuperNight_Scene_Preview \
    libCamera_s5kjnsmipiraw_Video_1080 \
    libCamera_s5kjnsmipiraw_Video_1080_60 \
    libCamera_s5kjnsmipiraw_Video_4k \
    libCamera_s5kjnsmipiraw_Video_Capture_4k \
    libCamera_s5kjnsmipiraw_Video_Capture_60 \
    libCamera_s5kjnsmipiraw_XTS_Capture \
    libCamera_s5kjnsmipiraw_Zoom_Capture \
    libCamera_s5kjnsmipiraw_Zoom_Preview \
    libCamera_s5kjnssunnymainmipiraw_3rd_Capture_mfnr \
    libCamera_s5kjnssunnymainmipiraw_3rd_Face_Capture_mfnr \
    libCamera_s5kjnssunnymainmipiraw_ASD_Capture \
    libCamera_s5kjnssunnymainmipiraw_ASD_Face_Capture \
    libCamera_s5kjnssunnymainmipiraw_ASD_Face_Preview \
    libCamera_s5kjnssunnymainmipiraw_ASD_Preview \
    libCamera_s5kjnssunnymainmipiraw_E2EHDR_Preview \
    libCamera_s5kjnssunnymainmipiraw_E2EHDR_Video \
    libCamera_s5kjnssunnymainmipiraw_FaceBeauty_Captute \
    libCamera_s5kjnssunnymainmipiraw_Face_Capture \
    libCamera_s5kjnssunnymainmipiraw_Face_Capture_Torch \
    libCamera_s5kjnssunnymainmipiraw_Face_Preview \
    libCamera_s5kjnssunnymainmipiraw_Flash_Capture \
    libCamera_s5kjnssunnymainmipiraw_Flash_Preview \
    libCamera_s5kjnssunnymainmipiraw_HDR_Capture \
    libCamera_s5kjnssunnymainmipiraw_HDR_Face_Capture \
    libCamera_s5kjnssunnymainmipiraw_HDR_Face_Preview \
    libCamera_s5kjnssunnymainmipiraw_HDR_Preview \
    libCamera_s5kjnssunnymainmipiraw_Manual_Capture \
    libCamera_s5kjnssunnymainmipiraw_Manual_Face_Capture \
    libCamera_s5kjnssunnymainmipiraw_Manual_Face_Preview \
    libCamera_s5kjnssunnymainmipiraw_Manual_Preview \
    libCamera_s5kjnssunnymainmipiraw_N3D_Capture \
    libCamera_s5kjnssunnymainmipiraw_N3D_Preview \
    libCamera_s5kjnssunnymainmipiraw_N3D_Video \
    libCamera_s5kjnssunnymainmipiraw_P1_YUV \
    libCamera_s5kjnssunnymainmipiraw_Portrait_Capture \
    libCamera_s5kjnssunnymainmipiraw_Portrait_Preview \
    libCamera_s5kjnssunnymainmipiraw_Scene_Capture \
    libCamera_s5kjnssunnymainmipiraw_Scene_Capture_4cell \
    libCamera_s5kjnssunnymainmipiraw_Scene_Capture_Torch \
    libCamera_s5kjnssunnymainmipiraw_Scene_Preview \
    libCamera_s5kjnssunnymainmipiraw_Scene_Preview_4k \
    libCamera_s5kjnssunnymainmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5kjnssunnymainmipiraw_SuperNight_Face_Capture \
    libCamera_s5kjnssunnymainmipiraw_SuperNight_Face_Preview \
    libCamera_s5kjnssunnymainmipiraw_SuperNight_Scene_Capture \
    libCamera_s5kjnssunnymainmipiraw_SuperNight_Scene_Preview \
    libCamera_s5kjnssunnymainmipiraw_Video_1080 \
    libCamera_s5kjnssunnymainmipiraw_Video_1080_60 \
    libCamera_s5kjnssunnymainmipiraw_Video_4k \
    libCamera_s5kjnssunnymainmipiraw_Video_Capture_4k \
    libCamera_s5kjnssunnymainmipiraw_Video_Capture_60 \
    libCamera_s5kjnssunnymainmipiraw_XTS_Capture \
    libCamera_s5kjnssunnymainmipiraw_Zoom_Capture \
    libCamera_s5kjnssunnymainmipiraw_Zoom_Preview \
    libCamera_sc202amipiraw_E2EHDR_Preview \
    libCamera_sc202amipiraw_E2EHDR_Video \
    libCamera_sc202amipiraw_Face_Capture \
    libCamera_sc202amipiraw_Flash_Capture \
    libCamera_sc202amipiraw_HDR_Capture \
    libCamera_sc202amipiraw_HDR_Preview \
    libCamera_sc202amipiraw_HDR_Reconfig_Preview \
    libCamera_sc202amipiraw_HDR_Reconfig_Video \
    libCamera_sc202amipiraw_HDR_Video \
    libCamera_sc202amipiraw_N3D_Capture \
    libCamera_sc202amipiraw_N3D_Preview \
    libCamera_sc202amipiraw_N3D_Video \
    libCamera_sc202amipiraw_P1_YUV \
    libCamera_sc202amipiraw_Scene_Capture \
    libCamera_sc202amipiraw_Scene_Capture_4cell \
    libCamera_sc202amipiraw_Scene_Preview \
    libCamera_sc202amipiraw_Scene_Preview_4k \
    libCamera_sc202amipiraw_Scene_Preview_ZSD_Flash \
    libCamera_sc202amipiraw_Video_1080 \
    libCamera_sc202amipiraw_Video_4k \
    libCamera_sc202amipiraw_XTS_Capture \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libMtkOmxCore \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libaal_key \
    libaal_mtk \
    libaedv \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libbwc \
    libcamalgo.utility \
    libcapctrl \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libconnfem \
    libcustom_nvram \
    libdynamiclog \
    libfile_op \
    libformatter \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libicd_decoder \
    libimgsensorca \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libladder \
    libminiui \
    libmml \
    libmmprofile \
    libmnetlink_v104 \
    libmtkares \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtklimiter_vendor \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtkshifter_vendor \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuroeara \
    libneuron_graph_delegate.mtk \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk \
    libnpagent \
    libnvram \
    libnvram_sec \
    libpixelflinger \
    libpqframework \
    librgbwlightsensor \
    libscltm \
    libsimlock \
    libsimmelock \
    libstagefrighthw \
    libstorage_otp \
    libsysenv \
    libtflite_mtk \
    libthha \
    libudf \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libvpu5 \
    meta_wifi_data \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.awb.core \
    lib3a.log \
    libIMGegl \
    libPVRMtkutils \
    libPVROCL \
    libPVRScopeServices \
    libaal_cust_func \
    libaalservice \
    libaiawb_moon_model \
    libaiawb_sun_model \
    libaiselector \
    libcam.hal3a.log \
    libcam.halsensor.hwintegration \
    libcamalgo.platform2 \
    libcameracustom.lens \
    libcameracustom \
    libdpframework \
    libgpudataproducer \
    libmemtrack_GL \
    libmpvr \
    libmtk_drvb \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam_debugutils \
    libmtkcam_metadata \
    libmtkcam_modulehelper \
    libmtkcam_stdutils \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libpqpconfig \
    libsrv_um \
    libufwriter \
    libusc \
    mtk000_mipi_raw_IdxMgr \
    mtk000_mipi_raw_tuning \
    s5k4h7_mipi_raw_IdxMgr \
    s5k4h7_mipi_raw_tuning \
    s5k4h7_sunny_front_mipi_raw_IdxMgr \
    s5k4h7_sunny_front_mipi_raw_tuning \
    s5kjns_mipi_raw_IdxMgr \
    s5kjns_mipi_raw_tuning \
    s5kjns_sunny_main_mipi_raw_IdxMgr \
    s5kjns_sunny_main_mipi_raw_tuning \
    sc202a_mipi_raw_IdxMgr \
    sc202a_mipi_raw_tuning \
    ov13b10main_mipi_raw_IdxMgr \
    ov48b_mipi_raw_IdxMgr \
    s5k2l7_mipi_raw_IdxMgr \
    s5k2lqsx_mipi_raw_IdxMgr \
    s5k2t7sp_mipi_raw_IdxMgr \
    s5k3m5sx_mipi_raw_IdxMgr \
    s5k3p9sp_mipi_raw_IdxMgr \
    s5k4h7front_mipi_raw_IdxMgr \
    sc800cs_mipi_raw_IdxMgr \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    libHEVCdec_sa.ca7.android \
    libMtkOmxAdpcmDec \
    libMtkOmxAlacDec \
    libMtkOmxApeDec \
    libMtkOmxGsmDec \
    libMtkOmxMp3Dec \
    libadpcmdec_mtk \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp3dec_mtk \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    librcs_interface \
    librcs_volte_core \
    libvcodec_utility_plat.mt6789 \
    libvcodec_utility_plat.mt6855 \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    libvcodec_utility \
    libvcodec_utility_v3a \
    libvcodecdrv \
    libvcodecdrv_v3a \
    libvpudv3a_vcodec \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    hq_algoutils \
    android.hardware.audio@6.0-impl-mediatek \
    android.hardware.audio@7.0-impl-mediatek \
    android.hardware.bluetooth@1.1-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    audio.primary.mediatek \
    audio.r_submix.mediatek \
    fingerprint.fpc.default \
    gps.default \
    hwcomposer.mtk_common \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    sensors.mediatek.V2.0 \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    lbs_hidl_service-impl \
    libArcNetMtk \
    libBSTHDRDETECT \
    libBSTMultiExpoGainHDR \
    libMcClient \
    libMtkSpeechEnh \
    libMtkSpeechEnh_swb \
    libNvEffectSdkCore \
    libTEECommon \
    libVkLayer_mtk_rt_sdk \
    lib_iir \
    lib_meishe_beauty \
    lib_single_bokeh \
    libalsautils-v31 \
    libarcsoft_faceid \
    libarcsoft_portrait_super_night_se_raw \
    libarcsoft_scbokeh_image \
    libarcsoft_scbokeh_video \
    libarcsoft_super_night_raw \
    libarcsoft_super_night_raw_bin \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libc++_shared \
    libcam.seninfn3d \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.lmv \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.warp \
    libcomposer_ext \
    libcvsd_mtk \
    libdecrypt \
    libfft_vendor \
    libfgauge_gm30 \
    libforkexecwrap \
    libgwsd-ril \
    libgwsdv2-ril \
    libgwsdv3-ril \
    libheichal \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libkmsetkey \
    libksensor \
    libmipc \
    libmmagent \
    libmpbase \
    libmsbc_mtk \
    libmtk-ril \
    libmtkcam_3rdparty.vidhance \
    libmtkcam_pipelinepolicy-aov \
    libmtkconfig \
    libmtkconfigutils \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtkrilutils \
    libmtkspparser \
    libmtkspparser_swb \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libnativebeautyrenderer \
    libneuron_platform \
    libnpagent_server \
    liboemcrypto \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librilfusion \
    librpc \
    librt_extamp_intf \
    libsdk_sr \
    libsn220u_fw \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libst_sr \
    libtlcWidevineModularDrm \
    libtrm \
    liburee_meta_drmkeyinstall \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvidhance \
    libvpu \
    libwifi-hal-mtk \
    libwifitest \
    libwpfa \
    libwvhidl \
    libmockdrmcryptoplugin \
    libwvdrmengine \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libDR \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    lib_bsscore \
    libaaa_ltm \
    libaaa_ltmx \
    libacdk \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.ispfeature \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.rotate \
    libcamalgo.vsf \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.plugin \
    libdip_drv \
    libdip_postproc \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmfllcore \
    libmnl \
    libmsnr \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libneuron_runtime.5 \
    libpda_usdriver \
    libstereoinfoaccessor_vsdof \
    libvainr_model \
    se_extn_client \
    libaudiopreprocessing \
    libaudiopreprocessing_mtk \
    libbundlewrapper \
    libdownmix \
    libdynproc \
    libeffectproxy \
    libhapticgenerator \
    libldnhncr \
    libreverbwrapper \
    libvisualizer \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.atci@1.0 \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libsignal \
    libsink \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    EuiccGoogle \
    MobileFeliCaClient \
    ImsService \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    com.fingerprints.extension \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.trustonic.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    gnss-mtk-default.xml \
    gnss-mtk@2.1-service.xml \
    lbs_hidl_service@1.0.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    manifest_hwcomposer.xml \
    manifest_media_c2_V1_2_default.xml \
    memtrack-mediatek.xml \
    atcid \
    audiocmdservice_atci \
    autobt \
    bip_ap \
    bt_dump \
    ccci_fsd \
    ccci_mdinit \
    ccci_rpcd \
    conninfra_loader \
    fpc_tee_test \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    hardware_revisions \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.memtrack-service.mediatek \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.security.keymint-service.trustonic \
    android.hardware.sensors@2.0-service.multihal-mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6855 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    init.insmod \
    ipsec_mon \
    lbs_hidl_service \
    mcDriverDaemon \
    mnld \
    mt6660_calibration \
    jpegtool \
    v3avpud.mt6855 \
    mtk_agpsd \
    muxreport \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    rt5512_calibration \
    stp_dump3 \
    volte_clientapi_ua \
    volte_rcs_ua \
    vpud \
    wifi_dump \
    wlan_assistant \
    wmt_launcher \
    wmt_loader \
    vtservice

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_graphics_allocator@4_0-service-mediatek \
    vendor_bin_hw_camerahalserver \
    vendor_bin_jpegtool \
    vendor_bin_v3avpud \
    vendor_lib_egl_libEGL_mtk_so \
    vendor_lib_egl_libGLESv1_CM_mtk_so \
    vendor_lib_egl_libGLESv2_mtk_so \
    vendor_lib_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib_hw_gralloc_rogue_so \
    vendor_lib_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib_hw_vendor_mediatek_hardware_camera_bgservice@1_1-impl_so \
    vendor_lib_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib_hw_vulkan_mtk_so \
    vendor_lib_lib3a_ae_core_so \
    vendor_lib_lib3a_ae_so \
    vendor_lib_lib3a_awb_core_so \
    vendor_lib_lib3a_log_so \
    vendor_lib_libIMGegl_so \
    vendor_lib_libPVRMtkutils_so \
    vendor_lib_libPVROCL_so \
    vendor_lib_libPVRScopeServices_so \
    vendor_lib_libaal_cust_func_so \
    vendor_lib_libaalservice_so \
    vendor_lib_libaiawb_moon_model_so \
    vendor_lib_libaiawb_sun_model_so \
    vendor_lib_libaiselector_so \
    vendor_lib_libcam_hal3a_log_so \
    vendor_lib_libcam_halsensor_hwintegration_so \
    vendor_lib_libcamalgo_platform2_so \
    vendor_lib_libcameracustom_lens_so \
    vendor_lib_libcameracustom_so \
    vendor_lib_libdpframework_so \
    vendor_lib_libgpudataproducer_so \
    vendor_lib_libmemtrack_GL_so \
    vendor_lib_libmpvr_so \
    vendor_lib_libmtk_drvb_so \
    vendor_lib_libmtkcam_atmseventmgr_so \
    vendor_lib_libmtkcam_eventcallback_so \
    vendor_lib_libmtkcam_debugutils_so \
    vendor_lib_libmtkcam_metadata_so \
    vendor_lib_libmtkcam_modulehelper_so \
    vendor_lib_libmtkcam_stdutils_so \
    vendor_lib_libmtkcam_sysutils_so \
    vendor_lib_libmtkcam_tuning_utils_so \
    vendor_lib_libmtkcam_ulog_so \
    vendor_lib_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib_libneuron_adapter_mgvi_so \
    vendor_lib_libnir_neon_driver_so \
    vendor_lib_libpq_cust_base_so \
    vendor_lib_libpq_prot_so \
    vendor_lib_libpqparamparser_so \
    vendor_lib_libpqpconfig_so \
    vendor_lib_libsrv_um_so \
    vendor_lib_libufwriter_so \
    vendor_lib_libusc_so \
    vendor_lib_libvcodec_utility_so \
    vendor_lib_libvcodec_utility_v3a_so \
    vendor_lib_libvcodecdrv_so \
    vendor_lib_libvcodecdrv_v3a_so \
    vendor_lib_libvpudv3a_vcodec_so \
    vendor_lib_mtk000_mipi_raw_IdxMgr_so \
    vendor_lib_mtk000_mipi_raw_tuning_so \
    vendor_lib_s5k4h7_mipi_raw_IdxMgr_so \
    vendor_lib_s5k4h7_mipi_raw_tuning_so \
    vendor_lib_s5k4h7_sunny_front_mipi_raw_IdxMgr_so \
    vendor_lib_s5k4h7_sunny_front_mipi_raw_tuning_so \
    vendor_lib_s5kjns_mipi_raw_IdxMgr_so \
    vendor_lib_s5kjns_mipi_raw_tuning_so \
    vendor_lib_s5kjns_sunny_main_mipi_raw_IdxMgr_so \
    vendor_lib_s5kjns_sunny_main_mipi_raw_tuning_so \
    vendor_lib_sc202a_mipi_raw_IdxMgr_so \
    vendor_lib_sc202a_mipi_raw_tuning_so \
    vendor_lib64_egl_libEGL_mtk_so \
    vendor_lib64_egl_libGLESv1_CM_mtk_so \
    vendor_lib64_egl_libGLESv2_mtk_so \
    vendor_lib64_hw_audio_primary_mt6855_so \
    vendor_lib64_hw_audio_r_submix_mt6855_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_gralloc_rogue_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_bgservice@1_1-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib64_hw_vulkan_mtk_so \
    vendor_lib64_hw_sensors_mt6855_so \
    vendor_lib64_lib3a_ae_core_so \
    vendor_lib64_lib3a_ae_so \
    vendor_lib64_lib3a_ae_stat_so \
    vendor_lib64_lib3a_af_assist_so \
    vendor_lib64_lib3a_af_assist_utils_so \
    vendor_lib64_lib3a_af_core_so \
    vendor_lib64_lib3a_af_so \
    vendor_lib64_lib3a_alsflicker_so \
    vendor_lib64_lib3a_awb_core_so \
    vendor_lib64_lib3a_ccudrv_so \
    vendor_lib64_lib3a_ccuif_so \
    vendor_lib64_lib3a_custom_ae_so \
    vendor_lib64_lib3a_dce_so \
    vendor_lib64_lib3a_flash_so \
    vendor_lib64_lib3a_flicker_so \
    vendor_lib64_lib3a_gma_so \
    vendor_lib64_lib3a_lce_so \
    vendor_lib64_lib3a_log_so \
    vendor_lib64_lib3a_n3d3a_so \
    vendor_lib64_lib3a_sensors_color_so \
    vendor_lib64_lib3a_sensors_flicker_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libIMGegl_so \
    vendor_lib64_libPVRMtkutils_so \
    vendor_lib64_libPVROCL_so \
    vendor_lib64_libPVRScopeServices_so \
    vendor_lib64_libSonyIMX230PdafLibrary_so \
    vendor_lib64_libSonyIMX230PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX338PdafLibrary_so \
    vendor_lib64_libSonyIMX338PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX386PdafLibrary_so \
    vendor_lib64_libSonyIMX386PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX519PdafLibrary_so \
    vendor_lib64_libSonyIMX519PdafLibraryWrapper_so \
    vendor_lib64_lib_bsscore_so \
    vendor_lib64_libaaa_ltm_so \
    vendor_lib64_libaaa_ltmx_so \
    vendor_lib64_libaal_cust_func_so \
    vendor_lib64_libaalservice_so \
    vendor_lib64_libacdk_so \
    vendor_lib64_libaiawb_moon_so \
    vendor_lib64_libaiawb_moon_model_so \
    vendor_lib64_libaiawb_p1ggm_so \
    vendor_lib64_libaiawb_sun_so \
    vendor_lib64_libaiawb_sun_model_so \
    vendor_lib64_libaibc_tuning_so \
    vendor_lib64_libaibc_tuning_p2_so \
    vendor_lib64_libaibc_tuning_p3_so \
    vendor_lib64_libaibc_tuning_p4_so \
    vendor_lib64_libaidepth_tuning_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libcam_afhal_so \
    vendor_lib64_libcam_chdr_so \
    vendor_lib64_libcam_feature_utils_so \
    vendor_lib64_libcam_hal3a_cctsvr_so \
    vendor_lib64_libcam_hal3a_log_so \
    vendor_lib64_libcam_hal3a_v3_ae_so \
    vendor_lib64_libcam_hal3a_v3_ai3a_so \
    vendor_lib64_libcam_hal3a_v3_awb_so \
    vendor_lib64_libcam_hal3a_v3_dng_so \
    vendor_lib64_libcam_hal3a_v3_fsmgr_so \
    vendor_lib64_libcam_hal3a_v3_lscMgr_so \
    vendor_lib64_libcam_hal3a_v3_lsctbl_50_so \
    vendor_lib64_libcam_hal3a_v3_nvram_50_so \
    vendor_lib64_libcam_hal3a_v3_platform_so \
    vendor_lib64_libcam_hal3a_v3_resultpool_so \
    vendor_lib64_libcam_hal3a_v3_so \
    vendor_lib64_libcam_halisp_buf_so \
    vendor_lib64_libcam_halisp_common_so \
    vendor_lib64_libcam_halisp_so \
    vendor_lib64_libcam_halsensor_hwintegration_so \
    vendor_lib64_libcam_halsensor_so \
    vendor_lib64_libcam_iopipe_so \
    vendor_lib64_libcam_isptuning_so \
    vendor_lib64_libcam_pdtblgen_so \
    vendor_lib64_libcam_tuning_cache_so \
    vendor_lib64_libcam_utils_sensorprovider_so \
    vendor_lib64_libcam_vhdr_so \
    vendor_lib64_libcamalgo_ispfeature_so \
    vendor_lib64_libcamalgo_lsc_so \
    vendor_lib64_libcamalgo_mfnr_so \
    vendor_lib64_libcamalgo_platform2_so \
    vendor_lib64_libcamalgo_rotate_so \
    vendor_lib64_libcamalgo_vsf_so \
    vendor_lib64_libcamdrv_isp_so \
    vendor_lib64_libcamdrv_tuning_mgr_so \
    vendor_lib64_libcamdrv_twin_so \
    vendor_lib64_libcamera_custom_pd_buf_mgr_so \
    vendor_lib64_libcamera_customae_so \
    vendor_lib64_libcamera_customaf_so \
    vendor_lib64_libcamera_customawb_so \
    vendor_lib64_libcamera_customflk_so \
    vendor_lib64_libcameracustom_camera_3a_so \
    vendor_lib64_libcameracustom_camera_isp_so \
    vendor_lib64_libcameracustom_camera_sensors_so \
    vendor_lib64_libcameracustom_camera_exif_so \
    vendor_lib64_libcameracustom_eis_so \
    vendor_lib64_libcameracustom_flashlight_so \
    vendor_lib64_libcameracustom_lens_so \
    vendor_lib64_libcameracustom_plugin_so \
    vendor_lib64_libcameracustom_so \
    vendor_lib64_libdip_drv_so \
    vendor_lib64_libdip_postproc_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libeffecthal_base_so \
    vendor_lib64_libfeature_face_so \
    vendor_lib64_libfeature_stereo_provider_so \
    vendor_lib64_libfeature_vsdof_hal_so \
    vendor_lib64_libfeature_3dnr_so \
    vendor_lib64_libfeature_eis_so \
    vendor_lib64_libfeature_fsc_so \
    vendor_lib64_libfeature_lmv_so \
    vendor_lib64_libfeature_rss_so \
    vendor_lib64_libfeatureiodrv_mem_so \
    vendor_lib64_libgpudataproducer_so \
    vendor_lib64_libimageio_so \
    vendor_lib64_libimageio_plat_drv_so \
    vendor_lib64_libimageio_plat_pipe_so \
    vendor_lib64_liblpcnr_so \
    vendor_lib64_libmemtrack_GL_so \
    vendor_lib64_libmfllcore_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmpvr_so \
    vendor_lib64_libmsnr_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libmtkcam_atmseventmgr_so \
    vendor_lib64_libmtkcam_eventcallback_so \
    vendor_lib64_libmtkcam_featurepipe_capture_so \
    vendor_lib64_libmtkcam_featurepipe_depthmap_so \
    vendor_lib64_libmtkcam_featurepipe_streaming_so \
    vendor_lib64_libmtkcam_featurepipe_vsdof_util_so \
    vendor_lib64_libmtkcam_logicalmodule_so \
    vendor_lib64_libmtkcam_3rdparty_core_so \
    vendor_lib64_libmtkcam_3rdparty_customer_so \
    vendor_lib64_libmtkcam_3rdparty_mtk_so \
    vendor_lib64_libmtkcam_3rdparty_so \
    vendor_lib64_libmtkcam_calibration_convertor_so \
    vendor_lib64_libmtkcam_calibration_provider_so \
    vendor_lib64_libmtkcam_debugutils_so \
    vendor_lib64_libmtkcam_device3_app_so \
    vendor_lib64_libmtkcam_device3_hal_so \
    vendor_lib64_libmtkcam_device3_hidl_so \
    vendor_lib64_libmtkcam_device3_hidlutils_so \
    vendor_lib64_libmtkcam_device3_utils_so \
    vendor_lib64_libmtkcam_devicesessionpolicy_so \
    vendor_lib64_libmtkcam_diputils_so \
    vendor_lib64_libmtkcam_exif_so \
    vendor_lib64_libmtkcam_fdvt_so \
    vendor_lib64_libmtkcam_featurepolicy_so \
    vendor_lib64_libmtkcam_featureutils_so \
    vendor_lib64_libmtkcam_fwkutils_so \
    vendor_lib64_libmtkcam_grallocutils_so \
    vendor_lib64_libmtkcam_hwnode_so \
    vendor_lib64_libmtkcam_hwutils_so \
    vendor_lib64_libmtkcam_imem_so \
    vendor_lib64_libmtkcam_imgbuf_so \
    vendor_lib64_libmtkcam_mapping_mgr_so \
    vendor_lib64_libmtkcam_metadata_so \
    vendor_lib64_libmtkcam_metastore_so \
    vendor_lib64_libmtkcam_mfb_so \
    vendor_lib64_libmtkcam_modulefactory_aaa_so \
    vendor_lib64_libmtkcam_modulefactory_custom_so \
    vendor_lib64_libmtkcam_modulefactory_drv_so \
    vendor_lib64_libmtkcam_modulefactory_utils_so \
    vendor_lib64_libmtkcam_modulehelper_so \
    vendor_lib64_libmtkcam_owe_so \
    vendor_lib64_libmtkcam_pipeline_so \
    vendor_lib64_libmtkcam_pipeline_fbm_so \
    vendor_lib64_libmtkcam_pipelinemodel_so \
    vendor_lib64_libmtkcam_pipelinemodel_adapter_so \
    vendor_lib64_libmtkcam_pipelinemodel_capture_so \
    vendor_lib64_libmtkcam_pipelinemodel_isp_so \
    vendor_lib64_libmtkcam_pipelinemodel_session_so \
    vendor_lib64_libmtkcam_pipelinemodel_utils_so \
    vendor_lib64_libmtkcam_pipelinemodel_zsl_so \
    vendor_lib64_libmtkcam_pipelinepolicy-security_so \
    vendor_lib64_libmtkcam_pipelinepolicy-smvr_so \
    vendor_lib64_libmtkcam_pipelinepolicy_so \
    vendor_lib64_libmtkcam_pipelinepolicy_factory_so \
    vendor_lib64_libmtkcam_prerelease_so \
    vendor_lib64_libmtkcam_rsc_so \
    vendor_lib64_libmtkcam_scenariorecorder_so \
    vendor_lib64_libmtkcam_stdutils_so \
    vendor_lib64_libmtkcam_streamutils_so \
    vendor_lib64_libmtkcam_synchelper_so \
    vendor_lib64_libmtkcam_sysutils_so \
    vendor_lib64_libmtkcam_tuning_utils_so \
    vendor_lib64_libmtkcam_ulog_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpda_usdriver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_prot_so \
    vendor_lib64_libpqparamparser_so \
    vendor_lib64_libpqpconfig_so \
    vendor_lib64_libsrv_um_so \
    vendor_lib64_libstereoinfoaccessor_vsdof_so \
    vendor_lib64_libufwriter_so \
    vendor_lib64_libusc_so \
    vendor_lib64_libvainr_model_so \
    vendor_lib64_mtk000_mipi_raw_IdxMgr_so \
    vendor_lib64_mtk000_mipi_raw_tuning_so \
    vendor_lib64_s5k4h7_mipi_raw_IdxMgr_so \
    vendor_lib64_s5k4h7_mipi_raw_tuning_so \
    vendor_lib64_s5k4h7_sunny_front_mipi_raw_IdxMgr_so \
    vendor_lib64_s5k4h7_sunny_front_mipi_raw_tuning_so \
    vendor_lib64_s5kjns_mipi_raw_IdxMgr_so \
    vendor_lib64_s5kjns_mipi_raw_tuning_so \
    vendor_lib64_s5kjns_sunny_main_mipi_raw_IdxMgr_so \
    vendor_lib64_s5kjns_sunny_main_mipi_raw_tuning_so \
    vendor_lib64_sc202a_mipi_raw_IdxMgr_so \
    vendor_lib64_sc202a_mipi_raw_tuning_so

PRODUCT_BOOT_JARS += \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base
